name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: build-step
        run: ci/build-app.sh