name: hello-world
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: checkout-step
        uses: actions/checkout@v2
      - name: build-step
        run: ci/build-app.sh
      - name: upload-repo
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
      - name: test-step
        run: ci/unit-test-app.sh
